// <auto-generated />
using System;
using BookReaderApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookReaderApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260531074743_AddFavoritesOnly")]
    partial class AddFavoritesOnly
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookReaderApi.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Tô Hoài",
                            CoverUrl = "https://example.com/de-men.jpg",
                            Title = "Dế Mèn Phiêu Lưu Ký"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Nguyễn Nhật Ánh",
                            CoverUrl = "https://example.com/hoa-vang.jpg",
                            Title = "Tôi Thấy Hoa Vàng Trên Cỏ Xanh"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Paulo Coelho",
                            CoverUrl = "https://example.com/nha-gia-kim.jpg",
                            Title = "Nhà Giả Kim"
                        });
                });

            modelBuilder.Entity("BookReaderApi.Models.Bookmark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("ChapterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("ChapterId");

                    b.ToTable("Bookmarks");
                });

            modelBuilder.Entity("BookReaderApi.Models.Chapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("Chapters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            Content = "Tôi sống độc lập từ thuở bé. Ấy là tục lệ lâu đời trong họ nhà dế chúng tôi. Mỗi chú dế khi lớn lên đều phải tự tìm cho mình một nơi ở riêng.",
                            Title = "Chương 1: Tôi sống độc lập từ thuở bé"
                        },
                        new
                        {
                            Id = 2,
                            BookId = 1,
                            Content = "Tôi từng rất kiêu căng và xem thường người khác. Chính sự kiêu căng ấy đã khiến tôi nhận được một bài học lớn trong cuộc đời.",
                            Title = "Chương 2: Bài học đường đời đầu tiên"
                        },
                        new
                        {
                            Id = 3,
                            BookId = 1,
                            Content = "Sau những biến cố đầu đời, tôi quyết định rời khỏi nơi ở quen thuộc để bắt đầu chuyến phiêu lưu khám phá thế giới rộng lớn.",
                            Title = "Chương 3: Cuộc phiêu lưu bắt đầu"
                        },
                        new
                        {
                            Id = 4,
                            BookId = 2,
                            Content = "Tuổi thơ là những ngày tháng trong veo, có cánh đồng, con đường làng và những người bạn thân thiết.",
                            Title = "Chương 1: Tuổi thơ"
                        },
                        new
                        {
                            Id = 5,
                            BookId = 2,
                            Content = "Mưa rơi trên mái nhà, trên hàng cây và trên những ký ức dịu dàng của tuổi nhỏ.",
                            Title = "Chương 2: Những ngày mưa"
                        },
                        new
                        {
                            Id = 6,
                            BookId = 2,
                            Content = "Trên bãi cỏ xanh, những bông hoa vàng nở rộ dưới ánh nắng. Đó là hình ảnh đẹp đẽ của tuổi thơ và tình bạn.",
                            Title = "Chương 3: Hoa vàng"
                        },
                        new
                        {
                            Id = 7,
                            BookId = 3,
                            Content = "Cậu bé chăn cừu luôn có một giấc mơ kỳ lạ về kho báu ở phương xa. Giấc mơ ấy thôi thúc cậu lên đường.",
                            Title = "Chương 1: Giấc mơ"
                        },
                        new
                        {
                            Id = 8,
                            BookId = 3,
                            Content = "Trên hành trình, cậu gặp nhiều người và học được nhiều bài học quý giá về cuộc sống.",
                            Title = "Chương 2: Hành trình"
                        },
                        new
                        {
                            Id = 9,
                            BookId = 3,
                            Content = "Sau bao thử thách, cậu nhận ra rằng kho báu lớn nhất chính là sự trưởng thành và hiểu biết về chính mình.",
                            Title = "Chương 3: Kho báu"
                        });
                });

            modelBuilder.Entity("BookReaderApi.Models.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId", "BookId")
                        .IsUnique();

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("BookReaderApi.Models.Bookmark", b =>
                {
                    b.HasOne("BookReaderApi.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BookReaderApi.Models.Chapter", "Chapter")
                        .WithMany()
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("BookReaderApi.Models.Chapter", b =>
                {
                    b.HasOne("BookReaderApi.Models.Book", "Book")
                        .WithMany("Chapters")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("BookReaderApi.Models.Favorite", b =>
                {
                    b.HasOne("BookReaderApi.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("BookReaderApi.Models.Book", b =>
                {
                    b.Navigation("Chapters");
                });
#pragma warning restore 612, 618
        }
    }
}
